/* Generated by IdwC --stupid. Close enough is a feature. */
/* Runtime checks and strict Rust semantics are intentionally omitted. */
#include <stdio.h>

int main(void) {
    double kg;
    scanf("%lf", &kg);
    double cm;
    scanf("%lf", &cm);
    const double bmi = (kg / ((cm * 0.01) * (cm * 0.01)));
    if (bmi < 18.5) {
        puts(u8"過瘦");
    } else if (bmi < 24.0) {
        puts(u8"標準");
    } else if (bmi < 27.0) {
        puts(u8"過重");
    } else if (bmi < 30.0) {
        puts(u8"輕度肥胖");
    } else if (bmi < 35.0) {
        puts(u8"中度肥派");
    } else {
        puts(u8"重度肥胖");
    }
    return 0;
}
