use std::collections::{BTreeSet, HashMap, HashSet};

use crate::TranspileOptions;
use crate::ir::{
    ArrayElement, BinaryOp, Expression, ExpressionKind, Function, Parameter, ParseSource,
    PrintFormat, Program, Statement, Type, UnaryOp,
};

/// Generates readable C17 while intentionally omitting strict Rust runtime checks.
pub(crate) fn generate(program: &Program, options: TranspileOptions) -> String {
    let function_names = allocate_function_names(&program.functions);
    let mut generator = Generator::new(&function_names, options);
    let mut prototypes = String::new();
    let mut functions = String::new();

    for function in &program.functions {
        generator.prepare_function(&function.parameters, &function.statements);
        generator.in_main = false;
        let signature = generator.function_signature(function);
        prototypes.push_str(&format!("{signature};\n"));
        generator.body.push_str(&format!("{signature} {{\n"));
        generator.indent = 1;
        generator.statements(&function.statements);
        if function.return_type == Type::Unit {
            generator.line("return;");
        }
        generator.body.push_str("}\n\n");
        functions.push_str(&generator.body);
        generator.body.clear();
    }

    generator.prepare_function(&[], &program.statements);
    generator.in_main = true;
    generator.indent = 1;
    generator.statements(&program.statements);
    generator.line("return 0;");
    let main_body = std::mem::take(&mut generator.body);

    let mut output = String::from(
        "/* Generated by IdwC --stupid. Close enough is a feature. */\n\
         /* Runtime checks and strict Rust semantics are intentionally omitted. */\n",
    );
    for header in ["stdbool.h", "stddef.h", "stdio.h", "stdlib.h", "string.h"] {
        if generator.includes.contains(header) {
            output.push_str(&format!("#include <{header}>\n"));
        }
    }
    output.push('\n');
    if !prototypes.is_empty() {
        output.push_str(&prototypes);
        output.push('\n');
        output.push_str(&functions);
    }
    output.push_str("int main(void) {\n");
    output.push_str(&main_body);
    output.push_str("}\n");
    output
}

/// State for one relaxed generation pass; binding IDs remain local to a Rust function.
struct Generator<'a> {
    body: String,
    indent: usize,
    next_temp: usize,
    includes: BTreeSet<&'static str>,
    function_names: &'a HashMap<usize, String>,
    binding_names: HashMap<usize, String>,
    token_length_names: HashMap<usize, String>,
    vec_length_names: HashMap<usize, String>,
    names: NameAllocator,
    in_main: bool,
    string_capacity: usize,
    vec_capacity: usize,
}

impl<'a> Generator<'a> {
    fn new(function_names: &'a HashMap<usize, String>, options: TranspileOptions) -> Self {
        Self {
            body: String::new(),
            indent: 1,
            next_temp: 0,
            includes: BTreeSet::new(),
            function_names,
            binding_names: HashMap::new(),
            token_length_names: HashMap::new(),
            vec_length_names: HashMap::new(),
            names: NameAllocator::default(),
            in_main: false,
            string_capacity: options.string_capacity(),
            vec_capacity: options.vec_capacity(),
        }
    }

    /// Allocates stable C names before emission so internal names never steal a source name.
    fn prepare_function(&mut self, parameters: &[Parameter], statements: &[Statement]) {
        self.binding_names.clear();
        self.token_length_names.clear();
        self.vec_length_names.clear();
        self.names = NameAllocator::default();
        self.next_temp = 0;
        for name in self.function_names.values() {
            self.names.used.insert(name.clone());
        }

        let mut bindings = parameters
            .iter()
            .map(|parameter| (parameter.id, parameter.name.clone(), parameter.ty))
            .collect::<Vec<_>>();
        collect_bindings(statements, &mut bindings);
        for (id, source_name, _) in &bindings {
            let name = self.names.allocate(source_name);
            self.binding_names.insert(*id, name);
        }
        for (id, _, ty) in bindings {
            if ty == Type::Tokens {
                let name = format!("{}_len", self.binding(id));
                let name = self.names.allocate(&name);
                self.token_length_names.insert(id, name);
            } else if matches!(ty, Type::Vec(_)) {
                let name = format!("{}_len", self.binding(id));
                let name = self.names.allocate(&name);
                self.vec_length_names.insert(id, name);
            }
        }
    }

    fn line(&mut self, line: &str) {
        self.body.push_str(&"    ".repeat(self.indent));
        self.body.push_str(line);
        self.body.push('\n');
    }

    fn binding(&self, id: usize) -> &str {
        self.binding_names
            .get(&id)
            .map(String::as_str)
            .expect("binding name must be allocated before generation")
    }

    fn temp_name(&mut self, purpose: &str) -> String {
        self.next_temp += 1;
        let suggested = if self.next_temp == 1 {
            purpose.to_owned()
        } else {
            format!("{purpose}_{}", self.next_temp)
        };
        self.names.allocate(&suggested)
    }

    fn statements(&mut self, statements: &[Statement]) {
        for statement in statements {
            match statement {
                Statement::Let {
                    id, mutable, value, ..
                } => self.let_statement(*id, *mutable, value),
                Statement::Assign { id, value } => self.assign(*id, value),
                Statement::AssignIndex {
                    id,
                    index,
                    value,
                    op,
                    ..
                } => {
                    let index = self.expression(index);
                    let value = self.expression(value);
                    let name = self.binding(*id).to_owned();
                    if let Some(op) = op {
                        self.line(&format!(
                            "{name}[{index}] {}= {value};",
                            binary_operator(*op)
                        ));
                    } else {
                        self.line(&format!("{name}[{index}] = {value};"));
                    }
                }
                Statement::VecAssignIndex { id, index, value } => {
                    // Rust evaluates the right-hand side before the place expression.
                    let value_text = self.expression(value);
                    let value_temp = self.temp_name("assigned_value");
                    self.line(&format!(
                        "const {} {value_temp} = {value_text};",
                        c_type(value.ty)
                    ));
                    let index_text = self.expression(index);
                    let index_temp = self.temp_name("index");
                    self.includes.insert("stddef.h");
                    self.line(&format!("const size_t {index_temp} = {index_text};"));
                    let name = self.binding(*id).to_owned();
                    self.line(&format!("{name}[{index_temp}] = {value_temp};"));
                }
                Statement::VecPush { id, value } => {
                    let value_text = self.expression(value);
                    let value_temp = self.temp_name("pushed_value");
                    self.line(&format!(
                        "const {} {value_temp} = {value_text};",
                        c_type(value.ty)
                    ));
                    let name = self.binding(*id).to_owned();
                    let length = self.vec_length(*id).to_owned();
                    self.line(&format!("{name}[{length}++] = {value_temp};"));
                }
                Statement::Block(statements) => {
                    self.line("{");
                    self.indent += 1;
                    self.statements(statements);
                    self.indent -= 1;
                    self.line("}");
                }
                Statement::If {
                    condition,
                    then_branch,
                    else_branch,
                } => self.if_statement(condition, then_branch, else_branch.as_deref()),
                Statement::While { condition, body } => self.while_loop(condition, body),
                Statement::ForRange {
                    id,
                    ty,
                    start,
                    end,
                    inclusive,
                    body,
                    ..
                } => self.for_range(*id, *ty, start, end, *inclusive, body),
                Statement::Loop(body) => {
                    self.line("for (;;) {");
                    self.indent += 1;
                    self.statements(body);
                    self.indent -= 1;
                    self.line("}");
                }
                Statement::Break => self.line("break;"),
                Statement::Continue => self.line("continue;"),
                Statement::Print {
                    parts,
                    arguments,
                    newline,
                } => self.print(parts, arguments, *newline),
                Statement::Return(value) => {
                    if let Some(value) = value {
                        if value.ty == Type::Unit {
                            self.discarded_expression(value);
                            self.line(if self.in_main { "return 0;" } else { "return;" });
                        } else {
                            let value = self.expression(value);
                            self.line(&format!("return {value};"));
                        }
                    } else {
                        self.line(if self.in_main { "return 0;" } else { "return;" });
                    }
                }
                Statement::Evaluate(value) => self.discarded_expression(value),
            }
        }
    }

    fn if_statement(
        &mut self,
        condition: &Expression,
        then_branch: &[Statement],
        else_branch: Option<&[Statement]>,
    ) {
        let condition = self.expression(condition);
        self.line(&format!("if {} {{", parenthesize(&condition)));
        self.indent += 1;
        self.statements(then_branch);
        self.indent -= 1;
        self.if_tail(else_branch);
    }

    fn if_tail(&mut self, else_branch: Option<&[Statement]>) {
        let Some(else_branch) = else_branch else {
            self.line("}");
            return;
        };
        if let [
            Statement::If {
                condition,
                then_branch,
                else_branch,
            },
        ] = else_branch
            && !expression_needs_prelude(condition)
        {
            let condition = self.expression(condition);
            self.line(&format!("}} else if {} {{", parenthesize(&condition)));
            self.indent += 1;
            self.statements(then_branch);
            self.indent -= 1;
            self.if_tail(else_branch.as_deref());
            return;
        }
        self.line("} else {");
        self.indent += 1;
        self.statements(else_branch);
        self.indent -= 1;
        self.line("}");
    }

    fn discarded_expression(&mut self, value: &Expression) {
        let before = self.body.len();
        let value_text = self.expression(value);
        if self.body.len() != before || matches!(&value.kind, ExpressionKind::Unit) {
            return;
        }
        if value.ty == Type::Unit {
            self.line(&format!("{value_text};"));
        } else {
            self.line(&format!("(void)({value_text});"));
        }
    }

    fn let_statement(&mut self, id: usize, mutable: bool, value: &Expression) {
        let name = self.binding(id).to_owned();
        match (&value.ty, &value.kind) {
            (Type::Str, ExpressionKind::StringLiteral(text)) => {
                self.line(&format!(
                    "const char *{name} = u8\"{}\";",
                    escape_readable_string(text, false)
                ));
            }
            (Type::Str, ExpressionKind::Variable(_)) => {
                let value = self.expression(value);
                let qualifier = if mutable { "" } else { "const " };
                self.line(&format!("{qualifier}char *{name} = {value};"));
            }
            (Type::String, ExpressionKind::StringNew) => {
                self.line(&format!(
                    "char {name}[{}] = \"\";",
                    self.string_capacity + 1
                ));
            }
            (Type::String, ExpressionKind::ReadString) => {
                self.includes.insert("stdio.h");
                self.line(&format!(
                    "char {name}[{}] = \"\";",
                    self.string_capacity + 1
                ));
                self.line(&format!("fgets({name}, sizeof({name}), stdin);"));
            }
            (Type::String, _) => {
                self.includes.insert("string.h");
                let source = self.string_source(value);
                self.line(&format!(
                    "char {name}[{}] = \"\";",
                    self.string_capacity + 1
                ));
                self.line(&format!("strcpy({name}, {source});"));
            }
            (Type::Tokens, ExpressionKind::SplitWhitespace(source)) => {
                self.tokens_let(id, *source);
            }
            (Type::Array(_, _), _) => self.array_let(id, mutable, value),
            (Type::Vec(_), _) => self.vec_let(id, value),
            (Type::I32, ExpressionKind::ReadI32) => {
                self.includes.insert("stdio.h");
                self.line(&format!("int {name};"));
                self.line(&format!("scanf(\"%d\", &{name});"));
            }
            (Type::F64, ExpressionKind::ReadF64) => {
                self.includes.insert("stdio.h");
                self.line(&format!("double {name};"));
                self.line(&format!("scanf(\"%lf\", &{name});"));
            }
            _ => {
                let initializer = self.expression(value);
                let qualifier = if mutable { "" } else { "const " };
                self.note_type(value.ty);
                self.line(&format!(
                    "{qualifier}{} {name} = {initializer};",
                    c_type(value.ty)
                ));
            }
        }
    }

    fn assign(&mut self, id: usize, value: &Expression) {
        if matches!(value.ty, Type::Array(_, _)) {
            self.array_assign(id, value);
            return;
        }
        if matches!(value.ty, Type::Vec(_)) {
            self.vec_assign(id, value);
            return;
        }
        let name = self.binding(id).to_owned();
        if value.ty == Type::String {
            if matches!(value.kind, ExpressionKind::ReadString) {
                self.includes.insert("stdio.h");
                self.line(&format!("{name}[0] = '\\0';"));
                self.line(&format!("fgets({name}, sizeof({name}), stdin);"));
            } else if matches!(value.kind, ExpressionKind::StringNew) {
                self.line(&format!("{name}[0] = '\\0';"));
            } else {
                self.includes.insert("string.h");
                let source = self.string_source(value);
                self.line(&format!("strcpy({name}, {source});"));
            }
            return;
        }
        if let ExpressionKind::Binary(op, left, right) = &value.kind
            && matches!(&left.kind, ExpressionKind::Variable(left_id) if *left_id == id)
            && matches!(
                op,
                BinaryOp::Add
                    | BinaryOp::Subtract
                    | BinaryOp::Multiply
                    | BinaryOp::Divide
                    | BinaryOp::Remainder
            )
        {
            let right = self.expression(right);
            self.line(&format!("{name} {}= {right};", binary_operator(*op)));
            return;
        }
        let value = self.expression(value);
        self.line(&format!("{name} = {value};"));
    }

    fn while_loop(&mut self, condition: &Expression, statements: &[Statement]) {
        let before = self.body.len();
        let condition = self.expression(condition);
        if self.body.len() == before {
            self.line(&format!("while {} {{", parenthesize(&condition)));
            self.indent += 1;
            self.statements(statements);
            self.indent -= 1;
            self.line("}");
            return;
        }
        let generated_condition = self.body.split_off(before);
        self.line("for (;;) {");
        self.indent += 1;
        self.body.push_str(&indent_block(&generated_condition, 1));
        self.line(&format!("if (!({condition})) {{"));
        self.indent += 1;
        self.line("break;");
        self.indent -= 1;
        self.line("}");
        self.statements(statements);
        self.indent -= 1;
        self.line("}");
    }

    fn for_range(
        &mut self,
        id: usize,
        ty: Type,
        start: &Expression,
        end: &Expression,
        inclusive: bool,
        statements: &[Statement],
    ) {
        self.note_type(ty);
        let start = self.expression(start);
        let end = self.expression(end);
        let name = self.binding(id).to_owned();
        let comparison = if inclusive { "<=" } else { "<" };
        self.line(&format!(
            "for ({} {name} = {start}; {name} {comparison} {end}; ++{name}) {{",
            c_type(ty)
        ));
        self.indent += 1;
        self.statements(statements);
        self.indent -= 1;
        self.line("}");
    }

    fn print(&mut self, parts: &[crate::ir::PrintPart], arguments: &[Expression], newline: bool) {
        self.includes.insert("stdio.h");
        if arguments.is_empty() {
            let text = parts
                .iter()
                .filter_map(|part| match part {
                    crate::ir::PrintPart::Text(text) => Some(text.as_str()),
                    _ => None,
                })
                .collect::<String>();
            let text = escape_readable_string(&text, false);
            if newline {
                self.line(&format!("puts(u8\"{text}\");"));
            } else {
                self.line(&format!("fputs(u8\"{text}\", stdout);"));
            }
            return;
        }
        if parts.iter().any(|part| {
            matches!(
                part,
                crate::ir::PrintPart::Argument {
                    format: PrintFormat::Debug,
                    ..
                }
            )
        }) {
            self.print_with_debug(parts, arguments, newline);
            return;
        }

        let mut format = String::new();
        let mut values = Vec::new();
        for part in parts {
            match part {
                crate::ir::PrintPart::Text(text) => {
                    format.push_str(&escape_readable_string(text, true));
                }
                crate::ir::PrintPart::Argument {
                    index,
                    format: style,
                } => {
                    let argument = &arguments[*index];
                    let value = self.expression(argument);
                    match argument.ty {
                        Type::I32 => format.push_str("%d"),
                        Type::Usize => format.push_str("%zu"),
                        Type::Bool => format.push_str("%s"),
                        Type::F64 => {
                            if let PrintFormat::Precision(precision) = style {
                                format.push_str(&format!("%.{precision}f"));
                            } else {
                                format.push_str("%g");
                            }
                        }
                        Type::Str | Type::String => format.push_str("%s"),
                        Type::Unit | Type::Array(_, _) | Type::Vec(_) | Type::Tokens => {
                            unreachable!("print arguments are validated as scalar")
                        }
                    }
                    values.push(if argument.ty == Type::Bool {
                        format!("({value}) ? \"true\" : \"false\"")
                    } else {
                        value
                    });
                }
            }
        }
        if newline {
            format.push_str("\\n");
        }
        self.line(&format!(
            "printf(u8\"{format}\"{});",
            if values.is_empty() {
                String::new()
            } else {
                format!(", {}", values.join(", "))
            }
        ));
    }

    fn print_with_debug(
        &mut self,
        parts: &[crate::ir::PrintPart],
        arguments: &[Expression],
        newline: bool,
    ) {
        let mut values = Vec::new();
        for argument in arguments {
            if matches!(argument.ty, Type::Array(_, _) | Type::Vec(_) | Type::String) {
                let ExpressionKind::Variable(id) = &argument.kind else {
                    unreachable!("aggregate print arguments are validated as bindings")
                };
                values.push(self.binding(*id).to_owned());
                continue;
            }
            let value = self.expression(argument);
            let temp = self.temp_name("printed_value");
            self.note_type(argument.ty);
            self.line(&format!("const {} {temp} = {value};", c_type(argument.ty)));
            values.push(temp);
        }

        for part in parts {
            match part {
                crate::ir::PrintPart::Text(text) if !text.is_empty() => {
                    self.line(&format!(
                        "fputs(u8\"{}\", stdout);",
                        escape_readable_string(text, false)
                    ));
                }
                crate::ir::PrintPart::Argument { index, format } => match format {
                    PrintFormat::Debug => self.debug_collection(&arguments[*index]),
                    PrintFormat::Precision(precision) => {
                        self.line(&format!("printf(\"%.{precision}f\", {});", values[*index]));
                    }
                    PrintFormat::Display => match arguments[*index].ty {
                        Type::I32 => {
                            self.line(&format!("printf(\"%d\", {});", values[*index]));
                        }
                        Type::Usize => {
                            self.line(&format!("printf(\"%zu\", {});", values[*index]));
                        }
                        Type::Bool => self.line(&format!(
                            "fputs({} ? \"true\" : \"false\", stdout);",
                            values[*index]
                        )),
                        Type::F64 => {
                            self.line(&format!("printf(\"%g\", {});", values[*index]));
                        }
                        Type::Str | Type::String => {
                            self.line(&format!("fputs({}, stdout);", values[*index]));
                        }
                        Type::Unit | Type::Array(_, _) | Type::Vec(_) | Type::Tokens => {
                            unreachable!("Display arguments are validated as scalar")
                        }
                    },
                },
                _ => {}
            }
        }
        if newline {
            self.line("putchar('\\n');");
        }
    }

    fn debug_collection(&mut self, argument: &Expression) {
        let ExpressionKind::Variable(id) = &argument.kind else {
            unreachable!("Debug collection arguments are validated as bindings")
        };
        let name = self.binding(*id).to_owned();
        let (element, length) = match argument.ty {
            Type::Array(element, length) => (element, length.to_string()),
            Type::Vec(element) => (element, self.vec_length(*id).to_owned()),
            _ => unreachable!("Debug arguments are validated as collections"),
        };
        self.includes.insert("stddef.h");
        self.line("putchar('[');");
        let index = self.temp_name("index");
        self.line(&format!(
            "for (size_t {index} = 0; {index} < {length}; ++{index}) {{"
        ));
        self.indent += 1;
        self.line(&format!("if ({index} != 0) {{ fputs(\", \", stdout); }}"));
        let item = format!("{name}[{index}]");
        match element {
            ArrayElement::I32 => self.line(&format!("printf(\"%d\", {item});")),
            ArrayElement::Usize => self.line(&format!("printf(\"%zu\", {item});")),
            ArrayElement::Bool => {
                self.line(&format!("fputs({item} ? \"true\" : \"false\", stdout);"));
            }
            ArrayElement::F64 => unreachable!("f64 Debug collection is rejected semantically"),
        }
        self.indent -= 1;
        self.line("}");
        self.line("putchar(']');");
    }

    fn expression(&mut self, expression: &Expression) -> String {
        match &expression.kind {
            ExpressionKind::Integer(value) => value.to_string(),
            ExpressionKind::Usize(value) => {
                self.includes.insert("stddef.h");
                format!("((size_t){value})")
            }
            ExpressionKind::Float(value) => readable_float(*value),
            ExpressionKind::Boolean(value) => {
                self.includes.insert("stdbool.h");
                value.to_string()
            }
            ExpressionKind::Variable(id) => self.binding(*id).to_owned(),
            ExpressionKind::Index { id, index, .. } => {
                let index = self.expression(index);
                format!("{}[{index}]", self.binding(*id))
            }
            ExpressionKind::ArrayLength(length) => {
                self.includes.insert("stddef.h");
                format!("((size_t){length})")
            }
            ExpressionKind::VecIndex { id, index } => {
                let index = self.expression(index);
                format!("{}[{index}]", self.binding(*id))
            }
            ExpressionKind::VecLength(id) => self.vec_length(*id).to_owned(),
            ExpressionKind::StringLiteral(value) => {
                format!("u8\"{}\"", escape_readable_string(value, false))
            }
            ExpressionKind::ReadI32 => self.read_value(Type::I32),
            ExpressionKind::ReadF64 => self.read_value(Type::F64),
            ExpressionKind::FlushStdout => {
                self.includes.insert("stdio.h");
                self.line("fflush(stdout);");
                "0".into()
            }
            ExpressionKind::Call(id, arguments) => {
                let arguments = arguments
                    .iter()
                    .map(|argument| self.expression(argument))
                    .collect::<Vec<_>>()
                    .join(", ");
                let name = self
                    .function_names
                    .get(id)
                    .cloned()
                    .unwrap_or_else(|| "main".into());
                format!("{name}({arguments})")
            }
            ExpressionKind::ReadLine(id) => {
                self.includes.extend(["stdio.h", "string.h"]);
                let name = self.binding(*id).to_owned();
                self.line(&format!(
                    "fgets({name} + strlen({name}), sizeof({name}) - strlen({name}), stdin);"
                ));
                "0".into()
            }
            ExpressionKind::TokensLength(id) => self.token_length(*id).to_owned(),
            ExpressionKind::Parse { source } => self.parse_value(expression.ty, source),
            ExpressionKind::Powi2(value) => {
                let value_text = self.expression(value);
                if reusable(value) {
                    format!("({value_text} * {value_text})")
                } else {
                    let temp = self.temp_name("pow_base");
                    self.line(&format!("double {temp} = {value_text};"));
                    format!("({temp} * {temp})")
                }
            }
            ExpressionKind::Unit => "0".into(),
            ExpressionKind::Unary(op, operand) => {
                let operand = self.expression(operand);
                match op {
                    UnaryOp::Negate => format!("(-{operand})"),
                    UnaryOp::Not => format!("(!{operand})"),
                }
            }
            ExpressionKind::Binary(op, left, right) => {
                let left = self.expression(left);
                let right = self.expression(right);
                format!("({left} {} {right})", binary_operator(*op))
            }
            ExpressionKind::Array(_)
            | ExpressionKind::ArrayRepeat(_, _)
            | ExpressionKind::Vec(_)
            | ExpressionKind::VecRepeat(_, _)
            | ExpressionKind::VecNew
            | ExpressionKind::StringNew
            | ExpressionKind::StringFrom(_)
            | ExpressionKind::ReadString
            | ExpressionKind::SplitWhitespace(_) => {
                unreachable!("aggregate expressions are emitted by their binding statement")
            }
        }
    }

    fn read_value(&mut self, ty: Type) -> String {
        self.includes.insert("stdio.h");
        let name = self.temp_name("input");
        let (c_type, format) = match ty {
            Type::I32 => ("int", "%d"),
            Type::F64 => ("double", "%lf"),
            _ => unreachable!("typed stdin only produces i32 or f64"),
        };
        self.line(&format!("{c_type} {name};"));
        format!("(scanf(\"{format}\", &{name}), {name})")
    }

    fn string_source(&mut self, value: &Expression) -> String {
        match &value.kind {
            ExpressionKind::StringFrom(source) => self.expression(source),
            ExpressionKind::Variable(id) => self.binding(*id).to_owned(),
            _ => unreachable!("owned String sources are validated before generation"),
        }
    }

    fn parse_value(&mut self, ty: Type, source: &ParseSource) -> String {
        self.includes.insert("stdlib.h");
        let source = match source {
            ParseSource::TrimmedString(id) => self.binding(*id).to_owned(),
            ParseSource::Token { id, index } => {
                let index = self.expression(index);
                format!("{}[{index}]", self.binding(*id))
            }
        };
        match ty {
            Type::I32 => format!("((int)strtol({source}, NULL, 10))"),
            Type::F64 => format!("strtod({source}, NULL)"),
            _ => unreachable!("parse target is validated as i32 or f64"),
        }
    }

    fn tokens_let(&mut self, id: usize, source: usize) {
        self.includes.extend(["stddef.h", "string.h"]);
        let name = self.binding(id).to_owned();
        let source = self.binding(source).to_owned();
        let length = self.token_length(id).to_owned();
        let token = self.temp_name("token");
        self.line(&format!("char *{name}[{}];", self.vec_capacity));
        self.line(&format!("size_t {length} = 0;"));
        self.line(&format!(
            "for (char *{token} = strtok({source}, \" \\t\\r\\n\\v\\f\"); {token} != NULL; {token} = strtok(NULL, \" \\t\\r\\n\\v\\f\")) {{"
        ));
        self.indent += 1;
        self.line(&format!("{name}[{length}++] = {token};"));
        self.indent -= 1;
        self.line("}");
    }

    fn token_length(&self, id: usize) -> &str {
        self.token_length_names
            .get(&id)
            .map(String::as_str)
            .expect("token length name must be allocated before generation")
    }

    fn vec_length(&self, id: usize) -> &str {
        self.vec_length_names
            .get(&id)
            .map(String::as_str)
            .expect("Vec length name must be allocated before generation")
    }

    fn vec_let(&mut self, id: usize, value: &Expression) {
        let Type::Vec(element) = value.ty else {
            unreachable!("vec_let only accepts Vec values")
        };
        self.note_type(element.ty());
        self.includes.insert("stddef.h");
        let name = self.binding(id).to_owned();
        let length = self.vec_length(id).to_owned();
        self.line(&format!(
            "{} {name}[{}];",
            c_element_type(element),
            self.vec_capacity
        ));
        self.line(&format!("size_t {length} = 0;"));
        self.vec_fill(&name, &length, value);
        self.line(&format!("(void){name};"));
        self.line(&format!("(void){length};"));
    }

    fn vec_assign(&mut self, id: usize, value: &Expression) {
        let Type::Vec(element) = value.ty else {
            unreachable!("vec_assign only accepts Vec values")
        };
        let target = self.binding(id).to_owned();
        let target_length = self.vec_length(id).to_owned();
        if matches!(value.kind, ExpressionKind::VecNew) {
            self.line(&format!("{target_length} = 0;"));
            return;
        }

        let temp = self.temp_name("vec_value");
        let temp_length = self.temp_name("vec_value_len");
        self.includes.insert("stddef.h");
        self.line(&format!(
            "{} {temp}[{}];",
            c_element_type(element),
            self.vec_capacity
        ));
        self.line(&format!("size_t {temp_length} = 0;"));
        self.vec_fill(&temp, &temp_length, value);
        self.line(&format!("{target_length} = {temp_length};"));
        let index = self.temp_name("copy_index");
        self.line(&format!(
            "for (size_t {index} = 0; {index} < {target_length}; ++{index}) {{"
        ));
        self.indent += 1;
        self.line(&format!("{target}[{index}] = {temp}[{index}];"));
        self.indent -= 1;
        self.line("}");
    }

    fn vec_fill(&mut self, target: &str, length: &str, value: &Expression) {
        match &value.kind {
            ExpressionKind::VecNew => {}
            ExpressionKind::Vec(values) => {
                for value in values {
                    let value = self.expression(value);
                    self.line(&format!("{target}[{length}++] = {value};"));
                }
            }
            ExpressionKind::VecRepeat(value, repeat_length) => {
                let value_text = self.expression(value);
                let repeated = self.temp_name("repeated_value");
                self.line(&format!(
                    "const {} {repeated} = {value_text};",
                    c_type(value.ty)
                ));
                let index = self.temp_name("repeat_index");
                self.line(&format!(
                    "for (size_t {index} = 0; {index} < {repeat_length}; ++{index}) {{"
                ));
                self.indent += 1;
                self.line(&format!("{target}[{length}++] = {repeated};"));
                self.indent -= 1;
                self.line("}");
            }
            ExpressionKind::Variable(source) => {
                let source_name = self.binding(*source).to_owned();
                let source_length = self.vec_length(*source).to_owned();
                let index = self.temp_name("copy_index");
                self.line(&format!(
                    "for (size_t {index} = 0; {index} < {source_length}; ++{index}) {{"
                ));
                self.indent += 1;
                self.line(&format!("{target}[{length}++] = {source_name}[{index}];"));
                self.indent -= 1;
                self.line("}");
            }
            _ => unreachable!("Vec values are validated before code generation"),
        }
    }

    fn array_let(&mut self, id: usize, mutable: bool, value: &Expression) {
        let Type::Array(element, length) = value.ty else {
            unreachable!("array binding must have an array type")
        };
        self.note_type(element.ty());
        let values = self.array_values(value);
        let qualifier = if mutable { "" } else { "const " };
        let initializer = if values.is_empty() {
            "0".into()
        } else {
            values.join(", ")
        };
        self.line(&format!(
            "{qualifier}{} {}[{}] = {{{initializer}}};",
            c_element_type(element),
            self.binding(id),
            length.max(1)
        ));
    }

    fn array_assign(&mut self, id: usize, value: &Expression) {
        let Type::Array(_, length) = value.ty else {
            unreachable!("array assignment must have an array type")
        };
        let values = self.array_values(value);
        let name = self.binding(id).to_owned();
        for (index, value) in values.into_iter().take(length).enumerate() {
            self.line(&format!("{name}[{index}] = {value};"));
        }
    }

    fn array_values(&mut self, value: &Expression) -> Vec<String> {
        let Type::Array(_, length) = value.ty else {
            unreachable!("array value must have an array type")
        };
        match &value.kind {
            ExpressionKind::Array(values) => {
                values.iter().map(|value| self.expression(value)).collect()
            }
            ExpressionKind::ArrayRepeat(value, repeat_length) => {
                debug_assert_eq!(length, *repeat_length);
                let expression = value.as_ref();
                let value = self.expression(expression);
                if reusable(expression) {
                    vec![value; length]
                } else {
                    let temp = self.temp_name("repeated_value");
                    self.line(&format!("{} {temp} = {value};", c_type(expression.ty)));
                    vec![temp; length]
                }
            }
            ExpressionKind::Variable(id) => {
                let name = self.binding(*id).to_owned();
                (0..length)
                    .map(|index| format!("{name}[{index}]"))
                    .collect()
            }
            _ => unreachable!("array values are validated before code generation"),
        }
    }

    fn function_signature(&mut self, function: &Function) -> String {
        self.note_type(function.return_type);
        let parameters = if function.parameters.is_empty() {
            "void".into()
        } else {
            function
                .parameters
                .iter()
                .map(|parameter| {
                    self.note_type(parameter.ty);
                    format!("{} {}", c_type(parameter.ty), self.binding(parameter.id))
                })
                .collect::<Vec<_>>()
                .join(", ")
        };
        format!(
            "{} {}({parameters})",
            c_type(function.return_type),
            self.function_names[&function.id]
        )
    }

    fn note_type(&mut self, ty: Type) {
        match ty {
            Type::Bool => {
                self.includes.insert("stdbool.h");
            }
            Type::Usize => {
                self.includes.insert("stddef.h");
            }
            Type::Array(element, _) => self.note_type(element.ty()),
            Type::Vec(element) => self.note_type(element.ty()),
            Type::I32 | Type::F64 | Type::Unit | Type::Str | Type::String | Type::Tokens => {}
        }
    }
}

#[derive(Default)]
struct NameAllocator {
    used: HashSet<String>,
}

impl NameAllocator {
    fn allocate(&mut self, source: &str) -> String {
        let base = if source.starts_with('_') {
            format!("rust{source}")
        } else if is_reserved_c_name(source) {
            format!("{source}_value")
        } else {
            source.to_owned()
        };
        if self.used.insert(base.clone()) {
            return base;
        }
        for suffix in 2.. {
            let candidate = format!("{base}_{suffix}");
            if self.used.insert(candidate.clone()) {
                return candidate;
            }
        }
        unreachable!()
    }
}

fn allocate_function_names(functions: &[Function]) -> HashMap<usize, String> {
    let mut allocator = NameAllocator::default();
    allocator.used.insert("main".into());
    functions
        .iter()
        .map(|function| (function.id, allocator.allocate(&function.name)))
        .collect()
}

fn collect_bindings(statements: &[Statement], bindings: &mut Vec<(usize, String, Type)>) {
    for statement in statements {
        match statement {
            Statement::Let {
                id, name, value, ..
            } => bindings.push((*id, name.clone(), value.ty)),
            Statement::ForRange {
                id, name, ty, body, ..
            } => {
                bindings.push((*id, name.clone(), *ty));
                collect_bindings(body, bindings);
            }
            Statement::Block(body) | Statement::Loop(body) => collect_bindings(body, bindings),
            Statement::If {
                then_branch,
                else_branch,
                ..
            } => {
                collect_bindings(then_branch, bindings);
                if let Some(else_branch) = else_branch {
                    collect_bindings(else_branch, bindings);
                }
            }
            Statement::While { body, .. } => collect_bindings(body, bindings),
            Statement::Assign { .. }
            | Statement::AssignIndex { .. }
            | Statement::VecAssignIndex { .. }
            | Statement::VecPush { .. }
            | Statement::Break
            | Statement::Continue
            | Statement::Print { .. }
            | Statement::Return(_)
            | Statement::Evaluate(_) => {}
        }
    }
}

fn c_type(ty: Type) -> &'static str {
    match ty {
        Type::I32 => "int",
        Type::Usize => "size_t",
        Type::F64 => "double",
        Type::Bool => "bool",
        Type::Str => "const char *",
        Type::Unit => "void",
        Type::Array(_, _) | Type::Vec(_) | Type::String | Type::Tokens => {
            unreachable!("aggregate values need declaration-specific C syntax")
        }
    }
}

fn c_element_type(element: ArrayElement) -> &'static str {
    c_type(element.ty())
}

fn binary_operator(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Subtract => "-",
        BinaryOp::Multiply => "*",
        BinaryOp::Divide => "/",
        BinaryOp::Remainder => "%",
        BinaryOp::Equal => "==",
        BinaryOp::NotEqual => "!=",
        BinaryOp::Less => "<",
        BinaryOp::LessEqual => "<=",
        BinaryOp::Greater => ">",
        BinaryOp::GreaterEqual => ">=",
        BinaryOp::And => "&&",
        BinaryOp::Or => "||",
    }
}

fn parenthesize(expression: &str) -> String {
    if expression.starts_with('(') && expression.ends_with(')') {
        expression.to_owned()
    } else {
        format!("({expression})")
    }
}

fn readable_float(value: f64) -> String {
    let text = format!("{value:?}");
    if text.contains(['.', 'e', 'E']) {
        text
    } else {
        format!("{text}.0")
    }
}

fn reusable(expression: &Expression) -> bool {
    matches!(
        &expression.kind,
        ExpressionKind::Integer(_)
            | ExpressionKind::Usize(_)
            | ExpressionKind::Float(_)
            | ExpressionKind::Boolean(_)
            | ExpressionKind::Variable(_)
    )
}

fn expression_needs_prelude(expression: &Expression) -> bool {
    match &expression.kind {
        ExpressionKind::ReadI32
        | ExpressionKind::ReadF64
        | ExpressionKind::FlushStdout
        | ExpressionKind::ReadString
        | ExpressionKind::ReadLine(_) => true,
        ExpressionKind::Index { index, .. } | ExpressionKind::VecIndex { index, .. } => {
            expression_needs_prelude(index)
        }
        ExpressionKind::Parse {
            source: ParseSource::Token { index, .. },
        } => expression_needs_prelude(index),
        ExpressionKind::Powi2(value) => expression_needs_prelude(value) || !reusable(value),
        ExpressionKind::Unary(_, value) => expression_needs_prelude(value),
        ExpressionKind::Binary(_, left, right) => {
            expression_needs_prelude(left) || expression_needs_prelude(right)
        }
        ExpressionKind::Call(_, arguments)
        | ExpressionKind::Array(arguments)
        | ExpressionKind::Vec(arguments) => arguments.iter().any(expression_needs_prelude),
        ExpressionKind::ArrayRepeat(value, _) | ExpressionKind::VecRepeat(value, _) => {
            expression_needs_prelude(value)
        }
        ExpressionKind::Integer(_)
        | ExpressionKind::Usize(_)
        | ExpressionKind::Float(_)
        | ExpressionKind::Boolean(_)
        | ExpressionKind::Variable(_)
        | ExpressionKind::ArrayLength(_)
        | ExpressionKind::VecNew
        | ExpressionKind::VecLength(_)
        | ExpressionKind::StringLiteral(_)
        | ExpressionKind::StringNew
        | ExpressionKind::StringFrom(_)
        | ExpressionKind::SplitWhitespace(_)
        | ExpressionKind::TokensLength(_)
        | ExpressionKind::Parse {
            source: ParseSource::TrimmedString(_),
        }
        | ExpressionKind::Unit => false,
    }
}

/// Preserves visible UTF-8 while escaping bytes that could alter a C string literal.
fn escape_readable_string(value: &str, printf_format: bool) -> String {
    let mut result = String::new();
    for character in value.chars() {
        match character {
            '"' => result.push_str("\\\""),
            '\\' => result.push_str("\\\\"),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            '?' => result.push_str("\\?"),
            '%' if printf_format => result.push_str("%%"),
            character if character.is_control() => {
                let mut bytes = [0; 4];
                for byte in character.encode_utf8(&mut bytes).bytes() {
                    result.push_str(&format!("\\{byte:03o}"));
                }
            }
            character => result.push(character),
        }
    }
    result
}

fn indent_block(block: &str, levels: usize) -> String {
    let prefix = "    ".repeat(levels);
    block
        .lines()
        .map(|line| format!("{prefix}{line}\n"))
        .collect()
}

fn is_reserved_c_name(name: &str) -> bool {
    name.starts_with("__")
        || name
            .strip_prefix('_')
            .and_then(|rest| rest.chars().next())
            .is_some_and(char::is_uppercase)
        || matches!(
            name,
            "auto"
                | "break"
                | "case"
                | "char"
                | "const"
                | "continue"
                | "default"
                | "do"
                | "double"
                | "else"
                | "enum"
                | "extern"
                | "float"
                | "for"
                | "goto"
                | "if"
                | "inline"
                | "int"
                | "long"
                | "register"
                | "restrict"
                | "return"
                | "short"
                | "signed"
                | "sizeof"
                | "static"
                | "struct"
                | "switch"
                | "typedef"
                | "union"
                | "unsigned"
                | "void"
                | "volatile"
                | "while"
                | "_Alignas"
                | "_Alignof"
                | "_Atomic"
                | "_Bool"
                | "_Complex"
                | "_Generic"
                | "_Imaginary"
                | "_Noreturn"
                | "_Static_assert"
                | "_Thread_local"
                | "bool"
                | "true"
                | "false"
                | "size_t"
                | "main"
                | "printf"
                | "puts"
                | "fputs"
                | "putchar"
                | "scanf"
                | "fflush"
                | "fgets"
                | "strtok"
                | "strtol"
                | "strtod"
                | "strlen"
                | "stdout"
                | "stdin"
                | "NULL"
        )
}

#[cfg(test)]
mod tests {
    use super::{NameAllocator, escape_readable_string};

    #[test]
    fn readable_strings_keep_unicode_and_escape_c_syntax() {
        assert_eq!(escape_readable_string("過瘦 100%", true), "過瘦 100%%");
        assert_eq!(
            escape_readable_string("\"\\\n??/", false),
            "\\\"\\\\\\n\\?\\?/"
        );
    }

    #[test]
    fn source_names_are_kept_until_they_conflict() {
        let mut allocator = NameAllocator::default();
        assert_eq!(allocator.allocate("score"), "score");
        assert_eq!(allocator.allocate("score"), "score_2");
        assert_eq!(allocator.allocate("int"), "int_value");
        assert_eq!(allocator.allocate("_hidden"), "rust_hidden");
    }
}
